<?php
$dictionary['MREQ_MEDB_Requests']['fields']['workflow_end_status_c'] = array (
            'required' => false,
            'name' => 'workflow_end_status_c',
            'vname' => 'LBL_WORKFLOW_END_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Open',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'workflow_end_status_list',
            'studio' => 'visible',
            'dependency' => false,
            'source' => 'custom_fields',
        );
