<?php
// $dictionary['DISC_Discovery']['fields']['witness_depo_c'] = 
//   array (
//     'required' => true,
//     'source' => 'non-db',
//     'name' => 'witness_depo_c',
//     'vname' => 'LBL_WITNESS_RELATE',
//     'type' => 'parent', 
//     'massupdate' => 0,
//     'no_default' => false,
//     'comments' => '',
//     'help' => '',
//     'importable' => 'true',
//     'duplicate_merge' => 'disabled',
//     'duplicate_merge_dom_value' => '0',
//     'audited' => false,
//     'inline_edit' => true,
//     'reportable' => true,
//     'unified_search' => false,
//     'merge_filter' => 'disabled',
//     'len' => 25,
//     'size' => '20',
//     'options' => 'parent_type_display',
//     'studio' => 'visible',
//     'type_name' => 'witness_type_c',
//     'id_name' => 'witness_id_c',
//     // 'witness_type_c' => 'record_type_display',
//   );
// $dictionary['DISC_Discovery']['fields']['witness_type_c'] = 
//   array (
//     'required' => false,
//     'name' => 'witness_type_c',
//     'vname' => 'LBL_WITNESS_TYPE',
//     'type' => 'witness_type_c',
//     'massupdate' => 0,
//     'no_default' => false,
//     'comments' => '',
//     'help' => '',
//     'importable' => 'true',
//     'duplicate_merge' => 'disabled',
//     'duplicate_merge_dom_value' => 0,
//     'audited' => false,
//     'inline_edit' => true,
//     'reportable' => true,
//     'unified_search' => false,
//     'merge_filter' => 'disabled',
//     'len' => 255,
//     'size' => '20',
//     'dbType' => 'varchar',
//     'studio' => 'hidden',
//     'source' => 'custom_fields',
//   );
//   $dictionary['DISC_Discovery']['fields']['witness_id_c'] = 
//   array (
//     'required' => false,
//     'name' => 'witness_id_c',
//     'vname' => 'LBL_WITNESS_ID',
//     'type' => 'id',
//     'massupdate' => 0,
//     'no_default' => false,
//     'comments' => '',
//     'help' => '',
//     'importable' => 'true',
//     'duplicate_merge' => 'disabled',
//     'duplicate_merge_dom_value' => 0,
//     'audited' => false,
//     'inline_edit' => true,
//     'reportable' => true,
//     'unified_search' => false,
//     'merge_filter' => 'disabled',
//     'len' => 36,
//     'size' => '20',
//     'source' => 'custom_fields',
//   );
?>