<?php
$dictionary['Document']['fields']['sentoutstatus_c'] = array (
            'required' => false,
            'name' => 'sentoutstatus_c',
            'vname' => 'LBL_SENTOUTSTATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Process',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'sentoutstatus_list',
            'studio' => 'visible',
            'dependency' => false,
            'source' => 'custom_fields',
        );
