<?php
$dictionary['AOW_Workflow']['fields']['workflow_score'] = array (
            'required' => true,
            'name' => 'workflow_score',
            'vname' => 'LBL_WORKFLOW_SCORE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'workflow_score_list',
            'studio' => 'visible',
            'dependency' => false,
        );
