<?php
$dictionary['Case']['fields']['workflow_not_done_c'] = array (
            'required' => false,
            'name' => 'workflow_not_done_c',
            'vname' => 'LBL_WORKFLOW_NOT_DONE_REASON',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            // 'len' => 255,
            'size' => '100',
            'options' => 'workflow_not_done_reason_list',
            'studio' => 'visible',
            'dependency' => false,
            'source' => 'custom_fields',
        );
